### ISSUE TITLE
Yarn run firefox fails when a tool is symlinked to the launchpad

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#116]
This happens because `start-firefox` points to the launchpad script, but `geckodriver` is installed locally. 

```
../../../devtools-core/packages/devtools-launchpad/bin/firefox-driver.js
```

```
➜  debugger.html yarn run firefox
yarn run v0.18.1
$ ./node_modules/.bin/start-firefox --start --location https://devtools-html.github.io/debugger-examples/
/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/node_modules/selenium-webdriver/firefox/index.js:298
    throw Error(
    ^

Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH.
    at findGeckoDriver (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/node_modules/selenium-webdriver/firefox/index.js:298:11)
    at ServiceBuilder (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/node_modules/selenium-webdriver/firefox/index.js:410:22)
    at createGeckoDriver (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/node_modules/selenium-webdriver/firefox/index.js:515:19)
    at Function.createSession (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/node_modules/selenium-webdriver/firefox/index.js:631:14)
    at createDriver (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/node_modules/selenium-webdriver/index.js:642:16)
    at start (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/bin/firefox-driver.js:70:6)
    at Object.<anonymous> (/Users/jlaster/src/mozilla/devtools-core/packages/devtools-launchpad/bin/firefox-driver.js:76:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this
```

**Comment by bomsy** [comment]
i noticed this late yesterday!
