### ISSUE TITLE
[Launchpad] error when installing deps in Win10

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/devtools-core#332]
node 7.4.0, npm 4.0.5, yarn 0.22.0

Error: Cannot find module 'C:\src\github.com\devtools-html\devtools-core\package
s\devtools-launchpad\node_modules\lib\lockfile\parse.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getGlobalYarnParser (C:\src\github.com\devtools-html\devtools-core\packag
es\devtools-launchpad\node_modules\parse-yarn-lock\src\index.js:25:18)
    at each (C:\src\github.com\devtools-html\devtools-core\packages\devtools-lau
nchpad\node_modules\run-waterfall\index.js:19:22)
    at LOOP (fs.js:1617:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

---

It works for me in OSX

Honza

**Comment by janodvarko** [comment]
More info:

If I remove `scripts/prebublish` field from `devtools-launchpad/package.json` it works.
So, what could be wrong with executing `node bin/validate-deps` ?

Honza

**Comment by clarkbw** [comment]
I was looking into this with the appveyor PR. It seems that the yarn lock parse module is failing. And that seems to be failing because something is wrong with the path it is getting back from the which module.
