### ISSUE TITLE
[Development Server] should support HTTPs requests

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#59]
The debugger currently cannot fetch source maps from debugger-example projects because github uses HTTPS.

STR:
* launch debugger `yarn start`
* launch firefox and go to `https://devtools-html.github.io/debugger-examples/examples/increment/`
* go to `localhost:8000` and select increment
* observe the terminal error below

This should be an easy fix here

```patch


diff --git a/packages/devtools-launchpad/bin/development-server.js b/packages/devtools-launchpad/bin/development-server.js
index 0825b80..31d9bea 100755
--- a/packages/devtools-launchpad/bin/development-server.js
+++ b/packages/devtools-launchpad/bin/development-server.js
@@ -18,6 +18,7 @@ const setConfig = require("devtools-config").setConfig;
 const isDevelopment = require("devtools-config").isDevelopment;

 function httpGet(url, onResponse) {
+  // we should also support https
   return http.get(url, (response) => {
     if (response.statusCode !== 200) {
       console.error(`error response: ${response.statusCode} to ${url}`);
diff --git a/packages/devtools-launchpad/webpack.config.js b/packages/devtools-launchpad/webpack.config.js
index b50f552..2dab874 100644
--- a/packages/devtools-launchpad/webpack.config.js
+++ b/packages/devtools-launchpad/webpack.config.js
@@ -48,7 +48,7 @@ module.exports = (webpackCo
```

To test this, you'll want to make the change in devtools-core and either re-install devtools-core or link the repos: [info](https://github.com/devtools-html/devtools-core#installing-locally)

Error:

```
Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:54:11)
    at Object.request (http.js:26:10)
    at Object.get (http.js:30:21)
    at httpGet (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/bin/development-server.js:21:15)
    at handleNetworkRequest (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/bin/development-server.js:48:21)
    at Layer.handle [as handle_request] (/Users/jlaster/src/mozilla/debugger.html/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jlaster/src/mozilla/debugger.html/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/jlaster/src/mozilla/debugger.html/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jlaster/src/mozilla/debugger.html/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jlaster/src/mozilla/debugger.html/node_modules/express/lib/router/index.js:277:22
```

**Comment by bomsy** [comment]
I would like to work on this!

**Comment by bomsy** [comment]
Cool
