### ISSUE TITLE
Sourcemapping url with a data uri - FF does not use the sourcemap.

### ISSUE THREAD

**Issue by raghur** [devtools-html/devtools-core#650]
I'm developing an app in vue.js with Karma and webpack. While debugging in browser, the sourcemap is specified with a //# sourcemappingurl = and a data uri with the source map. This seems to work fine in Chrome but not in FF (57). I prefer to use FF but in this case am forced to use Chrome. I checked bugzilla and googled a bit but it's unclear if there's a reason why firefox doesn't support this.

**Comment by tromey** [comment]
`data:` URLs were fixed a while back; if you are using 57 then they should be fine.  However, there are various other source map bugs still ... is your app available somewhere so I could try it?  I know nothing about vue, karma, ...

**Comment by raghur** [comment]
Repo - https://github.com/raghur/vue-testdrive

1. Clone repo
2. run `npm i`
3. run `node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js`
4. run `npm run test:debug`
This will run unit tests with karma on the console. Now you can browse to http://localhost:9876 (karma web console). There's a debug button - if you hit that you get a blank page. Open dev tools and look at `/base/test/index.js` which has a `//# sourcemappingurl`. Same thing on Chrome provides sourcemapped files.

**Comment by tromey** [comment]
I tried this, and indeed it doesn't work, but I also see errors while building the pack and errors from the server:

```
    ERROR in ./~/bootstrap/dist/css/bootstrap.css
    Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
        at Object.parseQuery (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-utils/lib/parseQuery.js:13:9)
        at Object.module.exports (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/css-loader/lib/loader.js:15:26)
     @ dll vendor
    
    ERROR in ./~/bootstrap/dist/css/bootstrap.css
    Module build failed: ModuleBuildError: Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
        at Object.parseQuery (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-utils/lib/parseQuery.js:13:9)
        at Object.module.exports (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/css-loader/lib/loader.js:15:26)
        at runLoaders (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/webpack/lib/NormalModule.js:192:19)
        at /home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-runner/lib/LoaderRunner.js:364:11
        at /home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-runner/lib/LoaderRunner.js:230:18
        at runSyncOrAsync (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
        at iterateNormalLoaders (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
        at /home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-runner/lib/LoaderRunner.js:202:4
        at /home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:62:14
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)
    Child extract-text-webpack-plugin:
        
        ERROR in ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css
        Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
            at Object.parseQuery (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-utils/lib/parseQuery.js:13:9)
            at Object.module.exports (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/css-loader/lib/loader.js:15:26)
```

Then later

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
      at Object.parseQuery (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/loader-utils/lib/parseQuery.js:13:9)
      at Object.module.exports (/home/tromey/firefox-git/Source-Maps/vue-testdrive/node_modules/css-loader/lib/loader.js:15:26)
  at test/index.js:3885
11 09 2017 08:41:25.942:WARN [reporter]: SourceMap position not found for trace: undefined
```

**Comment by raghur** [comment]
Yes - that doesn't look right. I just double checked and it looks like my `npm-shrinkwrap.json` was referring to a private feed which would have caused problems for you. Removed those and have pushed a commit. Also checked on a clean clone. Can you pull from the repo and try again?

**Comment by tromey** [comment]
I still get the webpack errors.

**Comment by tromey** [comment]
One thing that would be helpful is to know what file I should be able to see that I don't currently see.

**Comment by raghur** [comment]
Did you retry the `npm -i` after pulling? Also clean out `wwwroot/dist` before building vendor.js and/or running npm test:debug as well. I'm not quite sure why you're getting the errors - I've double checked on a clean env. Will try on my linux m/c tomorrow.

You should see a webpack built file at http://localhost:9876/base/test/index.js with the inline source map - this is served by Karma (in memory) and doesn't actually exist on the file system.

**Comment by tromey** [comment]
Yeah, I did re-run `npm` but to be sure, just now I:

```
rm -rf node_modules
rm -rf rm -rf wwwroot/dist/
npm i
node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js
```

... and I see those same errors.

**Comment by tromey** [comment]
I do see base/text/index.js in the debugger.  Which original sources should I be able to see?

**Comment by raghur** [comment]
You should see sources from `ClientApp/**/*.vue` or  `ClientApp/**/*.ts`. (On chrome, works as intended)

BTW, I re-ran everything on my linux box and it works without errors (npm run test:debug will spew out some errors the first time but they're harmless). For reference, I have

```
node --version
v7.10.1
node node_modules/webpack/bin/webpack.js --version
2.7.0
```

**Comment by tromey** [comment]
I do see those files, but they appear to have been mangled by webpack.  Like, the .vue files don't start with `<template>`. The .ts files look reasonable though.

**Comment by raghur** [comment]
here's how I get them in Chrome
![image](https://user-images.githubusercontent.com/516267/30630395-16b7c71c-9dfe-11e7-8271-e4841ffdf790.png)

And here's firefox nightly
![image](https://user-images.githubusercontent.com/516267/30630417-31272d7c-9dfe-11e7-8e79-6908cede3ee4.png)

**Comment by SwagMuffinMcYoloPants** [comment]
@raghur  Any news on this?  I've been having similar problems with source maps myself.

**Comment by raghur** [comment]
@SwagMuffinMcYoloPants - no nothing here though you'll have to ask @tromey. I have gone back to using Chrome for debugging and on to other stuff.

**Comment by tromey** [comment]
Sorry about the delay on this.  I'm not actively working on source maps now and so I've also lost some state.

@raghur I think in your screenshot, if you go to the `webpack://` part, you would see the original sources.

@SwagMuffinMcYoloPants what problems are you seeing; with what version of Firefox; and do you have a way to reproduce the problem?

**Comment by SwagMuffinMcYoloPants** [comment]
@tromey I have an application that's using Spring Security and the Javascript files require authentication  I just get an error saying that Firefox couldn't parse the source map because it's not valid JSON.  I take the Javascript code and move it outside the Spring Security enforced web app and the source maps load.  My only guess it that when it load the source maps, it's redirecting to the login page.  I don't have time right now to make an example today but I'll see if I can get a Docker instance up and running.

**Comment by tromey** [comment]
> the Javascript files require authentication

This sounds like a different bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1404245

**Comment by SwagMuffinMcYoloPants** [comment]
Thanks @tromey
