### ISSUE TITLE
Linking is not working

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#69]
We've seen several issues with linking the debugger to devtools-core packages

* `yarn link client-devtools-adapters`
* `yarn link devtools-modules`
* `yarn link devtools-launchpad`

Some of the reported issues are
* sources do not show up (likely an issue with client adapters)
* prefs is not defined (likely a devtools-modules issue)

It's possible to link multiple repos i.e. run `yarn link client-devtools-adapters` and `yarn link devtools-launchpad` which might be causing issues. 

Is it possible to run `yarn unlink client-devtools-adapters`? If so we might want to document that.
If not we should document the good old `rm -r node_modules` approach as devs should know how to uninstall.

**Comment by tromey** [comment]
I tried linking as suggested in the "Local Development" doc, and when I tried loading the debugger from the development server, I got:

```ERROR in ../devtools-core/packages/devtools-client-adapters/index.js
Module build failed: ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "base" at 0, attempted to resolve relative to "/home/tromey/ff-github/devtools-core/packages/devtools-client-adapters"
    at /home/tromey/ff-github/debugger.html/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/tromey/ff-github/debugger.html/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/tromey/ff-github/debugger.html/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/tromey/ff-github/debugger.html/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/tromey/ff-github/debugger.html/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/tromey/ff-github/debugger.html/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/tromey/ff-github/debugger.html/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/tromey/ff-github/debugger.html/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/home/tromey/ff-github/debugger.html/node_modules/babel-loader/lib/index.js:133:12)
 @ ./src/main.js 9:16-51
```

**Comment by clarkbw** [comment]
> I tried linking as suggested in the "Local Development" doc, and when I tried loading the debugger from the development server, I got:

I got this same error 👎

**Comment by juliandescottes** [comment]
What I already fixed in #21 was using linking for `devtools-launchpad`. **If you link only `devtools-launchpad`, it should work.**

When we link packages, the webpack bundle gets bigger. It contains duplicated versions of dependencies coming from the linked package. For #21 I just made sure that all dependencies could be properly deduped by our single module instance plugin (some of them were being transpiled in one case and not another).

I could keep patching our webpack config so that SMP dedupes everything correctly. But it would be nice if we could avoid getting duplicated dependencies when a package is linked. I'll see if I can find any way to fix it the root issue rather than patching the config.

**Comment by jasonLaster** [comment]
@clarkbw, @tromey, @Garbee, @wldcordeiro mind giving linking a try now?

You should be able to 
1. go to debugger.html, 
2. run yarn and then 
3. yarn link (devtools-launchpad|devtools-client-adapters|devtools_modules)...

**Comment by jasonLaster** [comment]
Here are two gifs of linking [devtools-modules](http://g.recordit.co/piY2PX98r5.gif) and [devtools-launchpad](http://g.recordit.co/LK550o1qs8.gif)

**Comment by jasonLaster** [comment]
closing as i think its working
