### ISSUE TITLE
Launching Firefox and Chrome both fail on Windows 10

### ISSUE THREAD

**Issue by digitarald** [devtools-html/devtools-core#749]
Running `yarn start` in Git Bash, navigating to launchpad, I only get a promise error when clicking launch Firefox:

```
(node:28400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not locate Firefox on the current system
(node:28400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28400) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

Different error happens when launching Chrome:

```
Error: spawn UNKNOWN
    at _errnoException (util.js:1019:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:494:9)
    at handleLaunchRequest (C:\Users\micro\dev\debugger.html\node_modules\devtools-launchpad\src\server\launch.js:35:8)
    at Layer.handle [as handle_request] (C:\Users\micro\dev\debugger.html\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\micro\dev\debugger.html\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\micro\dev\debugger.html\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\micro\dev\debugger.html\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\micro\dev\debugger.html\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\micro\dev\debugger.html\node_modules\express\lib\router\index.js:335:12)

```

**Comment by digitarald** [comment]
Probably related to https://github.com/yarnpkg/yarn/pull/3848, as https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/src/server/launch.js#L35 tries to execute the JS file and Windows doesn't know about the shebang notation.

**Comment by brutalcrozt** [comment]
For clarity, kindly remove 10 from windows 10. Since i verify it also fail on win 8. I wait pr number 775 land to work on. FF fail, perhaps the problem on the ff driver.js.

**Comment by brutalcrozt** [comment]
does /claim work here? I am in progress

**Comment by jasonLaster** [comment]
haha - the bot is not here. i'll summon it
