### ISSUE TITLE
webpack.config.js error when running in debugger.html

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/devtools-core#77]
In #74 a change to webpack.config.js is causing an error running the debugger.html.

I noted it here: https://github.com/devtools-html/devtools-core/commit/f0a17da28f2415fbd1526d71847100cc5d286a90#commitcomment-20430954

Not every item in `entry` is an array so the `push` method fails.  Not sure if the fix is here or the debugger config.

https://github.com/devtools-html/debugger.html/blob/master/webpack.config.js#L10-L14

Here's the error I'm seeing.

```bash
$ yarn start
yarn start v0.18.1
$ node bin/dev-server 
/Users/clarkbw/src/mozilla/debugger.html/node_modules/devtools-launchpad/webpack.config.js:92
        webpackConfig.entry[key].push("webpack-hot-middleware/client");
                                 ^

TypeError: webpackConfig.entry[key].push is not a function
    at Object.keys.forEach.key (/Users/clarkbw/src/mozilla/debugger.html/node_modules/devtools-launchpad/webpack.config.js:92:34)
    at Array.forEach (native)
    at Object.module.exports [as toolboxConfig] (/Users/clarkbw/src/mozilla/debugger.html/node_modules/devtools-launchpad/webpack.config.js:91:40)
    at buildConfig (/Users/clarkbw/src/mozilla/debugger.html/webpack.config.js:32:18)
    at Object.<anonymous> (/Users/clarkbw/src/mozilla/debugger.html/webpack.config.js:37:18)
    at Module._compile (module.js:571:32)
    at loader (/Users/clarkbw/src/mozilla/debugger.html/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/clarkbw/src/mozilla/debugger.html/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
error Command failed with exit code 1.
```

**Comment by clarkbw** [comment]
A change like this to the debugger webpack.config.js avoids the error and seems to allow the debugger to run correctly.

```diff
diff --git a/webpack.config.js b/webpack.config.js
index 7223525..b09dabb 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -8,10 +8,10 @@ function buildConfig(envConfig) {
   const webpackConfig = {
     entry: {
       debugger: [path.join(projectPath, "main.js")],
-      "source-map-worker": path.join(projectPath, "utils/source-map-worker.js"),
+      "source-map-worker": [path.join(projectPath, "utils/source-map-worker.js")],
       "pretty-print-worker":
-              path.join(projectPath, "utils/pretty-print-worker.js"),
-      "integration-tests": path.join(projectPath, "test/integration/tests.js"),
+              [path.join(projectPath, "utils/pretty-print-worker.js")],
+      "integration-tests": [path.join(projectPath, "test/integration/tests.js")],
     },
 
     output: {
```
